name: Update TG Subscribers to Notion

on:
  workflow_dispatch: # Запуск вручну
  schedule:
    - cron: "55 03 * * *" # Запуск щодня о 05:55 KUIV

jobs:
  update-subscribers:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Використовуємо Node.js версії 16

      - name: Install dependencies
        run: npm install node-telegram-bot-api @notionhq/client dotenv

      - name: Run script
        run: node index.js
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
